Added ec2 link for hw2
CT-CS5356-Fall2017/cs5356 pull request #341
Opened 2017-09-05 01:00 UTC by obanko01

2017-09-05 19:49 UTC, amfleming approved these changes

2017-09-05 20:08 UTC, rchatterjee commented
Hi @obanko01 Can you please resolve the conflicts?

2017-09-05 20:18 UTC, amfleming requested changes

2017-09-05 20:18 UTC, amfleming commented on README.md
> +* [Huajun Bai](people/huajun-bai.md) - hb364 - [https://s3.us-east-2.amazonaws.com/cs5356a1/grading.html](https://s3.us-east-2.amazonaws.com/cs5356a1/grading.html)
Whoops!  

Please only modify your own lines

2017-09-06 04:16 UTC, amfleming commented
No activity

2017-09-06 04:16 UTC, closed without merging