Updated link
CT-CS5356-Fall2017/cs5356 pull request #377
Opened 2017-09-05 19:16 UTC by zeeshanh

2017-09-05 20:47 UTC, amfleming approved these changes

2017-09-06 00:01 UTC, zeeshanh commented
Conflicts resolved.

2017-09-06 00:25 UTC, amfleming requested changes

2017-09-06 00:25 UTC, amfleming commented on README.md
> +* [Yuan Xuan](people/yuan-xuan.md) - yx424 - [http://www.tonyxuan26.com.s3-website.us-east-2.amazonaws.com/grading.html](http://www.tonyxuan26.com.s3-website.us-east-2.amazonaws.com/grading.html)
Why modifying `Yuan Xuan`?

2017-09-06 01:13 UTC, zeeshanh commented
Sorry about that, fixed it!

2017-09-06 01:37 UTC, merged