Assignment1
CT-CS5356-Fall2017/cs5356 pull request #86
Opened 2017-08-25 21:57 UTC by joe83830

jun-hsiang-liao jl3744

2017-08-25 22:09 UTC, amfleming requested changes
You need to pull from upstream to avoid conflicts

And don't delete the Alpha-order comment

2017-08-25 22:47 UTC, joe83830 commented
I modified the files

2017-08-25 22:52 UTC, amfleming requested changes
Yikes

2017-08-25 22:52 UTC, amfleming commented on README.md
> +
Why new line?

2017-08-25 22:52 UTC, amfleming commented on README.md
> +* [jun-hsiang-liao](people/jun-hsiang-liao.md) - jl3744 - [http://jl3744.xyz.s3-website.us-east-2.am    azonaws.com](http://jl3744.xyz.s3-website.us-east-2.amazonaws.com/grading.html)
Shouldn't this start with `[Jun Liao]` ?

2017-08-25 22:52 UTC, amfleming commented on README.md
> +>>>>>>> 67600b5a447043068f7b780c576b13d67e0341f4
What's this?

2017-08-25 22:52 UTC, amfleming commented on people/jun-hsiang-liao.md
> +Adam Fleming
Shouldn't this say `Jun Liao`?

2017-08-25 23:00 UTC, joe83830 commented
Sry I removed the weird thing on line 102.
I also Capitalized my name and removed the dashes in between.
But actually my name is Jun-Hsiang Liao, it's Mandarin so there are two words in my first name and this is how it appears on my passport.
I changed it to Jun Hsiang Liao.
Or should I combine it into sth like JunHsiang Liao?
Sorry for the trouble :P

2017-08-26 01:31 UTC, amfleming commented
Hi! You can spell your name however you want

I'm certain you don't spell it `Adam Fleming` however

2017-08-26 15:16 UTC, joe83830 commented
I think I corrected the format.
This is my first time forking things on GitHub, hope I finally got everything working, thanks!

2017-08-26 18:51 UTC, amfleming requested changes
Hi! Still have an accidental new line 

And people/junhsiang-liao.md still stays 'Adam Fleming'

2017-08-26 18:51 UTC, amfleming commented on people/junhsiang-liao.md
> +Adam Fleming
Still says `Adam Fleming` 😬

2017-08-26 19:57 UTC, joe83830 commented
Noooooo I'm terribly sorry sir I finally understood what you meant!

2017-08-27 12:38 UTC, merged